baseURL = "https://tqunhh.github.io/FCJ-report/"
languageCode = "en-us"
title = "Internship Report"

# ⚠️ KHÔNG dùng relativeURLs + canonifyURLs cho GitHub Pages
relativeURLs = false
canonifyURLs = false

# Theme
theme = "hugo-theme-learn"

# Build output
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# For search functionality
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  themeVariant = "workshop"
  editURL = ""
  description = ""
  author = "thienlh@thienlu.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false

########################
# Languages
########################
[languages]

[languages.en]
  title = "Internship Report"
  weight = 1
  languageName = "English"

  [[languages.en.menu.shortcuts]]
    name = "<i class='fab fa-facebook'></i> AWS Study Group"
    identifier = "AWS Study Group FB"
    url = "https://www.facebook.com/groups/awsstudygroupfcj/"
    weight = 20

[languages.vi]
  title = "Báo cáo thực tập"
  weight = 2
  languageName = "Tiếng Việt"

  [[languages.vi.menu.shortcuts]]
    name = "<i class='fab fa-facebook'></i> AWS Study Group"
    identifier = "AWS Study Group FB"
    url = "https://www.facebook.com/groups/awsstudygroupfcj/"
    weight = 20

########################
# Markdown / HTML
########################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
